server:
  port: 8888
spring:
  profiles:
    active: native
  application:
    name: configserver
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/common-config
eureka:
  client:
    instance:
      appname:
    serviceUrl:
      defaultZoon: http://localhost:8761/eureka/