spring:
  application:
    name: spring-cloud-provider2
  cloud:
    config:
      uri: http://localhost:8888
      discovery:
        enabled: true
        service-id: configserver
  sleuth:
    sampler:
      rate: 0
  zipkin:
    base-url: http://localhost:9411/
    sender:
      type: WEB
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 10000
    lettuce:
      pool:
        max-wait: 10000
eureka:
  client:
    serviceUrl:
      defaultZoon: http://localhost:8761/eureka/
server:
  port: 8083
management:
  endpoints:
    web:
      exposure:
        include: '*'
