spring:
  application:
    name: zuul-server
  sleuth:
    sampler:
      rate: 100
  zipkin:
    base-url: http://localhost:9411/
    sender:
      type: WEB
server:
  port: 8082
eureka:
  client:
    instance:
      appname:
    serviceUrl:
      defaultZoon: http://localhost:8761/eureka/
zuul:
  routes:
    spring-cloud-provider:
      path: /hello
      serviceId: spring-cloud-provider
    spring-cloud-provider2:
      path: /world
      serviceId: spring-cloud-provider2