spring:
  application:
    name: zuul-server
  sleuth:
    sampler:
      rate: 0
  zipkin:
    base-url: http://localhost:9411/
    sender:
      type: WEB
server:
  port: 8082
  servlet:
    session:
      cookie:
        domain: www.king.com
        path: /
        http-only: true
eureka:
  client:
    instance:
      appname:
    serviceUrl:
      defaultZoon: http://localhost:8761/eureka/
zuul:
  routes:
    spring-cloud-provider:
      path: /hello
      serviceId: spring-cloud-provider
    spring-cloud-provider2:
      path: /world
      serviceId: spring-cloud-provider2
    auth-server:
      path: /auth-server/**
      sensitiveHeaders:
      serviceId: auth-server
      strip-prefix: false
  sensitive-headers:
security:
  basic:
    enabled: false
  oauth2:
    client:
      access-token-uri: http://127.0.0.1:8091/auth-server/oauth/token
      user-authorization-uri: http://127.0.0.1:8091/auth-server/oauth/authorize
      client-id: fooClient
      client-secret: fooSecret
      use-current-uri: false
      pre-established-redirect-uri: http://www.king.com:8082/zuullogin
    resource:
      user-info-uri:  http://127.0.0.1:8091/auth-server/user
      prefer-token-info: false
    sso:
      login-path: /zuullogin
logging:
  level:
    org: debug
    com: debug
management:
  endpoints:
    web:
      exposure:
        include: '*'