spring:
  application:
    name: auth-server
  redis:
    host: 127.0.0.1
    port: 6379
server:
  port: 8091
  servlet:
    contextPath: /auth-server
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
  instance:
    prefer-ip-address: true
logging:
  level:
    org: debug
    com: debug
