spring:
  application:
    name: customer-client
  sleuth:
    sampler:
      rate: 100
  zipkin:
    base-url: http://localhost:9411/
    sender:
      type: WEB
server:
  port: 8090
eureka:
  client:
    instance:
      appname:
    serviceUrl:
      defaultZoon: http://localhost:8761/eureka/
feign:
  hystrix:
    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: '*'
security:
  basic:
    enabled: false
  oauth2:
    resource:
      user-info-uri:  http://127.0.0.1:8091/auth-server/user
      prefer-token-info: false